# Leave empty, otherwise it won't work with cusotm domains.
# Github will automatically fill in the correct string.
# Still, make sure to use {{ site.baseurl }} when using absolute paths.
baseurl: ""

title: "ITC 35"
conference-number: "35"
conference-name: "ITC 35"
conference-subname: "Networked Systems and Services"
conference-date: "3 - 5 October 2023"
conference-location: "Turin"
conference-location-detail: "Politecnico di Torino, Italy"
conference-domain: "https://itc35.itc-conference.org"
conference-mail: "itc35@lists.i-teletraffic.org"

# news pagination
paginate: 10
paginate_path: "/news/page:num/"

defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"

exclude: [ "Gemfile", "Gemfile.lock", "README.md" ]
theme: null
plugins:
    - jekyll-seo-tag

# deployment
host: 127.0.0.1
port: 4000
